#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f) uniform image2D testImg;
uniform vec2 aspect;
uniform vec2 posMin;
uniform vec2 posMax;

void main() {  
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	vec4 val = vec4(0.5);
	if (pixel.x == posMin.x && pixel.y == posMin.y)
		val = vec4(0.1);
	
	if (pixel.x == posMax.x && pixel.y == posMax.y)
		val = vec4(0.8);

	imageStore(testImg, pixel, val);
}